#!/usr/bin/python

SRC_PREFIX="/Users/mdday/src/openstack/"

repos = [     (SRC_PREFIX + "swift", "git://github.com/openstack/swift.git"),
              (SRC_PREFIX + "nova", "git://github.com/openstack/nova.git"),
              (SRC_PREFIX + "python-cinderclient", "git://github.com/openstack/python-cinderclient.git"),
              (SRC_PREFIX + "quantum", "git://github.com/openstack/quantum.git"),
              (SRC_PREFIX + "tempest", "git://github.com/openstack/tempest.git"),
              (SRC_PREFIX + "glance", "git://github.com/openstack/glance.git"), 
              (SRC_PREFIX + "python-keystoneclient", "git://github.com/openstack/python-keystoneclient.git"),
              (SRC_PREFIX + "openstack=manuals", "git://github.com/openstack/openstack-manuals.git"),
              (SRC_PREFIX + "heat", "git://github.com/openstack/heat.git"),
              (SRC_PREFIX + "cinder", "git://github.com/openstack/cinder.git"),              
              (SRC_PREFIX + "keystone", "git://github.com/openstack/keystone.git"),
              (SRC_PREFIX + "horizon", "git://github.com/openstack/horizon.git"),
              (SRC_PREFIX + "python-swiftclient", "git://github.com/openstack/python-swiftclient.git"),
              (SRC_PREFIX + "ceilometer", "git://github.com/openstack/ceilometer.git"),
              (SRC_PREFIX + "python-novaclient", "git://github.com/openstack/python-novaclient.git"),
              (SRC_PREFIX + "python-quantumclient", "git://github.com/openstack/python-quantumclient.git"),
              (SRC_PREFIX + "python-ceilometerclient", "git://github.com/openstack/python-ceilometerclient.git"),
              (SRC_PREFIX + "netconn-api", "git://github.com/openstack/netconn-api.git"),
              (SRC_PREFIX + "identity-api", "git://github.com/openstack/identity-api.git"),
              (SRC_PREFIX + "python-openstackclient", "git://github.com/openstack/python-openstackclient.git"),
              (SRC_PREFIX + "image-api", "git://github.com/openstack/image-api.git"),
              (SRC_PREFIX + "python-glanceclient", "git://github.com/openstack/python-glanceclient.git"),
              (SRC_PREFIX + "python-heatclient", "git://github.com/openstack/python-heatclient.git"),
              (SRC_PREFIX + "object-api", "git://github.com/openstack/object-api.git"),
              (SRC_PREFIX + "compute-api", "git://github.com/openstack/compute-api.git"),
              (SRC_PREFIX + "oslo-incubator", "git://github.com/openstack/oslo-incubator.git"),
              (SRC_PREFIX + "api-site", "git://github.com/openstack/api-site.git"),
              (SRC_PREFIX + "oslo-config", "git://github.com/openstack/oslo-config.git"),
              (SRC_PREFIX + "volume-api", "git://github.com/openstack/volume-api.git")]
